apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-service-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "pods/portforward"]
    verbs: ["get", "watch", "list", "create"]
